//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.elhackaton.appcede.ui;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import com.elhackaton.appcede.R.id;
import com.elhackaton.appcede.R.layout;
import com.elhackaton.appcede.app.reviews.ReviewClient_;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class NewReviewUI_
    extends NewReviewUI
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.newreview);
    }

    private void init_(Bundle savedInstanceState) {
        client = new ReviewClient_();
    }

    private void afterSetContentView_() {
        places = ((Spinner) findViewById(id.places));
        review = ((Spinner) findViewById(id.review));
        ok = ((Button) findViewById(id.ok));
        body = ((EditText) findViewById(id.body));
        category = ((Spinner) findViewById(id.category));
        place = ((EditText) findViewById(id.place));
        {
            View view = findViewById(id.picture);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewReviewUI_.this.takePicture();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.ok);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        NewReviewUI_.this.send();
                    }

                }
                );
            }
        }
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static NewReviewUI_.IntentBuilder_ intent(Context context) {
        return new NewReviewUI_.IntentBuilder_(context);
    }

    @Override
    public void closeDialog(final int message) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    NewReviewUI_.super.closeDialog(message);
                } catch (RuntimeException e) {
                    Log.e("NewReviewUI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void sendReview() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    NewReviewUI_.super.sendReview();
                } catch (RuntimeException e) {
                    Log.e("NewReviewUI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, NewReviewUI_.class);
        }

        public Intent get() {
            return intent_;
        }

        public NewReviewUI_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
