//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.elhackaton.appcede.ui;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageView;
import android.widget.TextView;
import com.elhackaton.appcede.R.layout;
import com.elhackaton.appcede.app.reviews.Review;
import com.elhackaton.appcede.app.reviews.ReviewClient_;
import com.googlecode.androidannotations.api.BackgroundExecutor;

public final class ReviewUI_
    extends ReviewUI
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.review);
    }

    private void init_(Bundle savedInstanceState) {
        client = new ReviewClient_();
    }

    private void afterSetContentView_() {
        address = ((TextView) findViewById(com.elhackaton.appcede.R.id.address));
        image = ((ImageView) findViewById(com.elhackaton.appcede.R.id.image));
        title = ((TextView) findViewById(com.elhackaton.appcede.R.id.title));
        afterView();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ReviewUI_.IntentBuilder_ intent(Context context) {
        return new ReviewUI_.IntentBuilder_(context);
    }

    @Override
    public void setReview(final Review review, final Bitmap bitmap, final String address) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ReviewUI_.super.setReview(review, bitmap, address);
                } catch (RuntimeException e) {
                    Log.e("ReviewUI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadReview(final int id) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ReviewUI_.super.loadReview(id);
                } catch (RuntimeException e) {
                    Log.e("ReviewUI_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ReviewUI_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ReviewUI_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
